//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for PetKind.
const (
	Bird    PetKind = "bird"
	Cat     PetKind = "cat"
	Dog     PetKind = "dog"
	Fish    PetKind = "fish"
	Reptile PetKind = "reptile"
)

// Valid indicates whether the value is a known member of the PetKind enum.
func (e PetKind) Valid() bool {
	switch e {
	case Bird:
		return true
	case Cat:
		return true
	case Dog:
		return true
	case Fish:
		return true
	case Reptile:
		return true
	default:
		return false
	}
}

// Defines values for ProblemErrorIn.
const (
	Body   ProblemErrorIn = "body"
	Header ProblemErrorIn = "header"
	Path   ProblemErrorIn = "path"
	Query  ProblemErrorIn = "query"
)

// Valid indicates whether the value is a known member of the ProblemErrorIn enum.
func (e ProblemErrorIn) Valid() bool {
	switch e {
	case Body:
		return true
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	default:
		return false
	}
}

// NewPet defines model for NewPet.
type NewPet struct {
	Age  int32   `json:"age" validate:"gte=0,lte=100"`
	Kind PetKind `json:"kind" validate:"required,oneof=dog cat fish bird reptile"`
	Name string  `json:"name" validate:"required,min=1,max=255"`
}

// Pet defines model for Pet.
type Pet struct {
	Age       int32     `json:"age"`
	CreatedAt time.Time `json:"createdAt"`
	ID        int64     `json:"id"`
	Kind      PetKind   `json:"kind"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// PetKind defines model for PetKind.
type PetKind string

// PetPage defines model for PetPage.
type PetPage struct {
	Items      []Pet   `json:"items"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail   *string         `json:"detail,omitempty"`
	Errors   *[]ProblemError `json:"errors,omitempty"`
	Instance *string         `json:"instance,omitempty"`
	Status   int32           `json:"status"`
	Title    string          `json:"title"`
	Type     string          `json:"type"`
}

// ProblemError defines model for ProblemError.
type ProblemError struct {
	Detail string         `json:"detail"`
	In     ProblemErrorIn `json:"in"`
	Name   string         `json:"name"`
	Rule   string         `json:"rule"`
}

// ProblemErrorIn defines model for ProblemError.In.
type ProblemErrorIn string

// UpdatePet defines model for UpdatePet.
type UpdatePet struct {
	Age  *int32   `json:"age,omitempty" validate:"omitempty,gte=0,lte=100"`
	Kind *PetKind `json:"kind,omitempty" validate:"omitempty,oneof=dog cat fish bird reptile"`
	Name *string  `json:"name,omitempty" validate:"omitempty,min=1,max=255"`
}

// PetsListPetsParams defines parameters for PetsListPets.
type PetsListPetsParams struct {
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty" validate:"omitempty,gte=1,lte=200"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// PetsCreatePetJSONRequestBody defines body for PetsCreatePet for application/json ContentType.
type PetsCreatePetJSONRequestBody = NewPet

// PetsUpdatePetJSONRequestBody defines body for PetsUpdatePet for application/json ContentType.
type PetsUpdatePetJSONRequestBody = UpdatePet

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	HealthHealthCheck(w http.ResponseWriter, r *http.Request)

	// (GET /pets)
	PetsListPets(w http.ResponseWriter, r *http.Request, params PetsListPetsParams)

	// (POST /pets)
	PetsCreatePet(w http.ResponseWriter, r *http.Request)

	// (DELETE /pets/{petId})
	PetsDeletePet(w http.ResponseWriter, r *http.Request, petID int64)

	// (GET /pets/{petId})
	PetsGetPet(w http.ResponseWriter, r *http.Request, petID int64)

	// (PUT /pets/{petId})
	PetsUpdatePet(w http.ResponseWriter, r *http.Request, petID int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// HealthHealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthHealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthHealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PetsListPets operation middleware
func (siw *ServerInterfaceWrapper) PetsListPets(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PetsListPetsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PetsListPets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PetsCreatePet operation middleware
func (siw *ServerInterfaceWrapper) PetsCreatePet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PetsCreatePet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PetsDeletePet operation middleware
func (siw *ServerInterfaceWrapper) PetsDeletePet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "petId" -------------
	var petID int64

	err = runtime.BindStyledParameterWithOptions("simple", "petId", r.PathValue("petId"), &petID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "petId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PetsDeletePet(w, r, petID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PetsGetPet operation middleware
func (siw *ServerInterfaceWrapper) PetsGetPet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "petId" -------------
	var petID int64

	err = runtime.BindStyledParameterWithOptions("simple", "petId", r.PathValue("petId"), &petID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "petId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PetsGetPet(w, r, petID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PetsUpdatePet operation middleware
func (siw *ServerInterfaceWrapper) PetsUpdatePet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "petId" -------------
	var petID int64

	err = runtime.BindStyledParameterWithOptions("simple", "petId", r.PathValue("petId"), &petID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "petId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PetsUpdatePet(w, r, petID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.HealthHealthCheck)
	m.HandleFunc("GET "+options.BaseURL+"/pets", wrapper.PetsListPets)
	m.HandleFunc("POST "+options.BaseURL+"/pets", wrapper.PetsCreatePet)
	m.HandleFunc("DELETE "+options.BaseURL+"/pets/{petId}", wrapper.PetsDeletePet)
	m.HandleFunc("GET "+options.BaseURL+"/pets/{petId}", wrapper.PetsGetPet)
	m.HandleFunc("PUT "+options.BaseURL+"/pets/{petId}", wrapper.PetsUpdatePet)

	return m
}

type HealthHealthCheckRequestObject struct {
}

type HealthHealthCheckResponseObject interface {
	VisitHealthHealthCheckResponse(w http.ResponseWriter) error
}

type HealthHealthCheck200JSONResponse struct {
	Status string `json:"status"`
}

func (response HealthHealthCheck200JSONResponse) VisitHealthHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PetsListPetsRequestObject struct {
	Params PetsListPetsParams
}

type PetsListPetsResponseObject interface {
	VisitPetsListPetsResponse(w http.ResponseWriter) error
}

type PetsListPets200JSONResponse PetPage

func (response PetsListPets200JSONResponse) VisitPetsListPetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PetsCreatePetRequestObject struct {
	Body *PetsCreatePetJSONRequestBody
}

type PetsCreatePetResponseObject interface {
	VisitPetsCreatePetResponse(w http.ResponseWriter) error
}

type PetsCreatePet201JSONResponse Pet

func (response PetsCreatePet201JSONResponse) VisitPetsCreatePetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PetsCreatePet400ApplicationProblemPlusJSONResponse Problem

func (response PetsCreatePet400ApplicationProblemPlusJSONResponse) VisitPetsCreatePetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PetsDeletePetRequestObject struct {
	PetID int64 `json:"petId"`
}

type PetsDeletePetResponseObject interface {
	VisitPetsDeletePetResponse(w http.ResponseWriter) error
}

type PetsDeletePet204Response struct {
}

func (response PetsDeletePet204Response) VisitPetsDeletePetResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PetsDeletePet404ApplicationProblemPlusJSONResponse Problem

func (response PetsDeletePet404ApplicationProblemPlusJSONResponse) VisitPetsDeletePetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PetsGetPetRequestObject struct {
	PetID int64 `json:"petId"`
}

type PetsGetPetResponseObject interface {
	VisitPetsGetPetResponse(w http.ResponseWriter) error
}

type PetsGetPet200JSONResponse Pet

func (response PetsGetPet200JSONResponse) VisitPetsGetPetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PetsGetPet404ApplicationProblemPlusJSONResponse Problem

func (response PetsGetPet404ApplicationProblemPlusJSONResponse) VisitPetsGetPetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PetsUpdatePetRequestObject struct {
	PetID int64 `json:"petId"`
	Body  *PetsUpdatePetJSONRequestBody
}

type PetsUpdatePetResponseObject interface {
	VisitPetsUpdatePetResponse(w http.ResponseWriter) error
}

type PetsUpdatePet200JSONResponse Pet

func (response PetsUpdatePet200JSONResponse) VisitPetsUpdatePetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PetsUpdatePet400ApplicationProblemPlusJSONResponse Problem

func (response PetsUpdatePet400ApplicationProblemPlusJSONResponse) VisitPetsUpdatePetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PetsUpdatePet404ApplicationProblemPlusJSONResponse Problem

func (response PetsUpdatePet404ApplicationProblemPlusJSONResponse) VisitPetsUpdatePetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /health)
	HealthHealthCheck(ctx context.Context, request HealthHealthCheckRequestObject) (HealthHealthCheckResponseObject, error)

	// (GET /pets)
	PetsListPets(ctx context.Context, request PetsListPetsRequestObject) (PetsListPetsResponseObject, error)

	// (POST /pets)
	PetsCreatePet(ctx context.Context, request PetsCreatePetRequestObject) (PetsCreatePetResponseObject, error)

	// (DELETE /pets/{petId})
	PetsDeletePet(ctx context.Context, request PetsDeletePetRequestObject) (PetsDeletePetResponseObject, error)

	// (GET /pets/{petId})
	PetsGetPet(ctx context.Context, request PetsGetPetRequestObject) (PetsGetPetResponseObject, error)

	// (PUT /pets/{petId})
	PetsUpdatePet(ctx context.Context, request PetsUpdatePetRequestObject) (PetsUpdatePetResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// HealthHealthCheck operation middleware
func (sh *strictHandler) HealthHealthCheck(w http.ResponseWriter, r *http.Request) {
	var request HealthHealthCheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HealthHealthCheck(ctx, request.(HealthHealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthHealthCheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthHealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthHealthCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PetsListPets operation middleware
func (sh *strictHandler) PetsListPets(w http.ResponseWriter, r *http.Request, params PetsListPetsParams) {
	var request PetsListPetsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PetsListPets(ctx, request.(PetsListPetsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PetsListPets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PetsListPetsResponseObject); ok {
		if err := validResponse.VisitPetsListPetsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PetsCreatePet operation middleware
func (sh *strictHandler) PetsCreatePet(w http.ResponseWriter, r *http.Request) {
	var request PetsCreatePetRequestObject

	var body PetsCreatePetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PetsCreatePet(ctx, request.(PetsCreatePetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PetsCreatePet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PetsCreatePetResponseObject); ok {
		if err := validResponse.VisitPetsCreatePetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PetsDeletePet operation middleware
func (sh *strictHandler) PetsDeletePet(w http.ResponseWriter, r *http.Request, petID int64) {
	var request PetsDeletePetRequestObject

	request.PetID = petID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PetsDeletePet(ctx, request.(PetsDeletePetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PetsDeletePet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PetsDeletePetResponseObject); ok {
		if err := validResponse.VisitPetsDeletePetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PetsGetPet operation middleware
func (sh *strictHandler) PetsGetPet(w http.ResponseWriter, r *http.Request, petID int64) {
	var request PetsGetPetRequestObject

	request.PetID = petID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PetsGetPet(ctx, request.(PetsGetPetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PetsGetPet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PetsGetPetResponseObject); ok {
		if err := validResponse.VisitPetsGetPetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PetsUpdatePet operation middleware
func (sh *strictHandler) PetsUpdatePet(w http.ResponseWriter, r *http.Request, petID int64) {
	var request PetsUpdatePetRequestObject

	request.PetID = petID

	var body PetsUpdatePetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PetsUpdatePet(ctx, request.(PetsUpdatePetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PetsUpdatePet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PetsUpdatePetResponseObject); ok {
		if err := validResponse.VisitPetsUpdatePetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RXW2/bNhT+K8TZ3qbYspsMhYA8dN2wFS02A+2egjzQ4rHFliJZ8ii1Yei/DyTlu5zG",
	"WwAvL5Fjkefyfd+5eAWlqa3RqMlDsQJfVljz+PFP/DZBCp+sMxYdSYzf8zmGx8y4mhMUIDW9GkMGNV/I",
	"uqmhGOV5BrXU6b88A1paTAdxjg4yWFwZbuVVaQTOUV/hghy/Ij6P9h+4koJTuDEnvM0zRXg7ynNo2wy+",
	"SC1iEEr9NYPibgU/OpxBAT8Mt4kMuyyGE6T34UJ7/3SfDr820qHIjEYzuxVmzkpObCZ9xabSCebQklQY",
	"w9G8jmDUfPEB9ZwqKMY3NzH79f+jTf6enNRz+Beh1FLfjrKaL27HNzfQBs/rd1DcpSg6bLLIz/3GqZl+",
	"xpKgzeAsMg8oazMoHXJC8Yb2zodIr0hG//tpthlIcWj75+te22tWn8TlFvUjh40V58V4AKQM+B2juZv8",
	"rpMTKL/vskEd9H8HwgTSSx4uBxlBBkFIEHwnKd33gDdBmnTs7FMmCev9D9+BLVjrzHPn+DJCiAt62zhv",
	"XA+Qh6hEP73JOjNVWB/HKJC4VL0coXPGnRF/cvFbuNWXiNSeuC73Vdw42adHT5wa/0S9kyTVr7L0xffc",
	"HYAY366tbkJ5BNSU8TnISr2ruqkRS8jga4MuPC2nILwKuUDXK7iTVeWaXiD6m5DU0N3I1rH2Jfl3LKJL",
	"zxdTBw1aWmaXmDRb75cfNdtYembNAXtt1NrMJDn60klL0mgo4A0LRhQnZBMk9pGMQ/Zm8o5NG6mIfZNU",
	"sU9Lix8tlhnbjSxjXAvmv6pysKmSAvaMQAYP6HzyNBrkQUbGouZWQgGvBvkg73QekxtWyFVAZQXzJLMg",
	"Mh4ifSeggD/i6/T3bYXll9iPvTXaJx2O8zw8SqMJdTTArVWyjCaGn73R24XpWMXbXvN42ZxsBOHgPrqf",
	"KmThKnpiFffMN2WJKFAMwuk2g6HFtMX1JjxB8h+kp/CMQDleI2HoxXcrwIVVRiAUM648pmayaR5Je6Bk",
	"LcMQ2+Z8ukjHe0U6erYiHcUiHXdF+gw2npZ6mWblbu6HvN7/R/18p73EZeBsVWRgjT8hhrdxqQk9OEkS",
	"Pf0ShsZzBd39gDhYV8k12B5BNXpOqM6CKTYezjR+Yw69aVyJ8cAUUbNu72PcMx5eN4oGoe9cP8qtTRP8",
	"pzMD75apE8F7dA/oWGkaJZg2xBot0IXlRzDaSU40yMgwqaP8mV9q4ou9DjFcWaR3ok39WyFhvz5+je+S",
	"Pg66RSyRbqXoKiTahEOmTzWL+EPgkfbQV07XxwPnU4UOmfRMG9aREZL3qAWbGceokn6NTMamDUWo0hLk",
	"Wc2XbIqs8Thr1IAlYq8vRSzXgdWZ3OcTxUaWXUGfbO6/I/1/yMovVtCDF8KjbU7wuN2NL0bl8w+DbVJP",
	"mgcXl8+L6+8vQPPBRrqR1Lxv74MpuWICH1AZW4dOns5CBo1TUEBFZIvhUIVzlfFUvM5f59Det/8EAAD/",
	"/ytms0LFFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
