// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPet = `-- name: CreatePet :one
INSERT INTO pets (name, kind, age)
VALUES ($1, $2, $3)
RETURNING id, name, kind, age, created_at, updated_at
`

type CreatePetParams struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
	Age  int32  `json:"age"`
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, createPet, arg.Name, arg.Kind, arg.Age)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Age,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePet = `-- name: DeletePet :execrows
DELETE FROM pets WHERE id = $1
`

func (q *Queries) DeletePet(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPet = `-- name: GetPet :one
SELECT id, name, kind, age, created_at, updated_at
FROM pets
WHERE id = $1
`

func (q *Queries) GetPet(ctx context.Context, id int64) (Pet, error) {
	row := q.db.QueryRow(ctx, getPet, id)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Age,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPets = `-- name: ListPets :many
SELECT id, name, kind, age, created_at, updated_at
FROM pets
WHERE ($1::bigint IS NULL OR id < $1)
ORDER BY id DESC
LIMIT $2
`

type ListPetsParams struct {
	Cursor   pgtype.Int8 `json:"cursor"`
	LimitVal int32       `json:"limit_val"`
}

func (q *Queries) ListPets(ctx context.Context, arg ListPetsParams) ([]Pet, error) {
	rows, err := q.db.Query(ctx, listPets, arg.Cursor, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pet{}
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Age,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePet = `-- name: UpdatePet :one
UPDATE pets
SET
    name = COALESCE($2, name),
    kind = COALESCE($3, kind),
    age = COALESCE($4, age),
    updated_at = now()
WHERE id = $1
RETURNING id, name, kind, age, created_at, updated_at
`

type UpdatePetParams struct {
	ID   int64       `json:"id"`
	Name pgtype.Text `json:"name"`
	Kind pgtype.Text `json:"kind"`
	Age  pgtype.Int4 `json:"age"`
}

func (q *Queries) UpdatePet(ctx context.Context, arg UpdatePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, updatePet,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Age,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Age,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
